apiVersion: apps/v1
kind: Deployment
metadata:
  name: hfh-wp-dash
  labels:
    app: hfh-wp-dash
  namespace: hfh
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: hfh-wp-dash
  template:
    metadata:
      labels:
        app: hfh-wp-dash
      namespace: hfh
    spec:
      containers:
      - name: hfh-wp-dash
        image: igorsyn/whatsapp-notification-dashboard:latest  # Substituir ${REGISTRY_URL} pelo nome do seu registro
        imagePullPolicy: Always  # Alterado para Always para garantir a versão mais recente
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: RefreshInterval
          value: "60000"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=cnpg-cluster-rw.cnpg-system.svc.cluster.local;Port=5432;Database=bpo;Username=postgres;Password=@qowtaw%7hyzGacyvtug#;SSL Mode=Disable"
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 12  # Permite até 1 minuto (12 * 5s) para inicialização


